# Generated by Django 2.1.5 on 2019-01-19 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creator',
            new_name='user',
        ),
    ]
