# Generated by Django 2.1.5 on 2019-01-19 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190119_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_time',
            new_name='date_created',
        ),
    ]
