# Generated by Django 2.1.5 on 2019-01-20 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdvInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_twitter_handle', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_location', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='lang',
        ),
        migrations.AddField(
            model_name='user',
            name='adv_info',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='post_like', to='core.UserAdvInfo'),
        ),
    ]
