# Generated by Django 2.1.5 on 2019-01-20 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190120_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adv_info',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='post_like', to='core.UserAdvInfo'),
        ),
    ]
